language: node_js
services:
  - mongodb
node_js:
  - '0.10'
before_script:
  - sleep 15
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - todd@sparkfun.com
    on_success: change
    on_failure: change
